---
- name: Load GitHub App secrets authentication setup
  ansible.builtin.import_tasks: auth.yml
  when: server_secrets_auth_method | default('github_app') == 'github_app'

- name: Load private secrets repository
  ansible.builtin.import_tasks: source.yml
