services:
  whatsupdocker:
    image: getwud/wud
    container_name: wud
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/shared/docker-data/wud/store:/store
    environment:
      WUD_AUTH_OIDC_AUTHENTIK_CLIENTID: ${WUD_AUTH_OIDC_AUTHENTIK_CLIENTID:-}
      WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET: ${WUD_AUTH_OIDC_AUTHENTIK_CLIENTSECRET:-}
      WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY: ${WUD_AUTH_OIDC_AUTHENTIK_DISCOVERY:-}
      WUD_AUTH_OIDC_AUTHENTIK_REDIRECT: true
      WUD_PUBLIC_URL: ${WUD_PUBLIC_URL:-}
      WUD_WATCHER_LOCAL_CRON: "0 3 * * *"
      WUD_WATCHER_LOCAL_WATCHBYDEFAULT: false
      WUD_TRIGGER_DOCKER_ACCOUNTMANAGER_AUTO: true
      WUD_TRIGGER_DOCKER_ACCOUNTMANAGER_PRUNE: true
      WUD_TRIGGER_DOCKER_EMAILTEMPLATES_AUTO: true
      WUD_TRIGGER_DOCKER_EMAILTEMPLATES_PRUNE: true
      WUD_TRIGGER_DOCKER_EVENTMANAGER_AUTO: true
      WUD_TRIGGER_DOCKER_EVENTMANAGER_PRUNE: true
      WUD_TRIGGER_DOCKER_KEYCLOAK_AUTO: true
      WUD_TRIGGER_DOCKER_KEYCLOAK_PRUNE: true
    healthcheck:
      test: curl --fail http://localhost:${WUD_SERVER_PORT:-3000}/health || exit 1
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.wud-updater.entryPoints=websecure, web"
      - "traefik.http.routers.wud-updater.rule=Host(`wud.cacic.dev.br`)"
      - "traefik.http.routers.wud-updater.tls=true"
      - "traefik.http.routers.wud-updater.tls.certResolver=letsencrypt"
      - "traefik.http.routers.wud-updater.service=wud-updater-svc"
      - "traefik.http.services.wud-updater-svc.loadBalancer.server.port=3000"
      - 'wud.tag.include=^\d+\.\d+\.\d+$$'
      - "wud.link.template=https://github.com/getwud/wud/releases/tag/$${major}.$${minor}.$${patch}"
    networks:
      - traefik

networks:
  traefik:
    external: true
