---
- name: Apply compose projects
  ansible.builtin.include_tasks: deploy-project.yml
  loop: "{{ compose_projects }}"
  loop_control:
    loop_var: compose_project
    label: "{{ compose_project }}"
