---
- name: Clone external service repositories
  ansible.builtin.git:
    repo: "{{ item.repo }}"
    dest: "{{ docker_compose_root }}/{{ item.name }}"
    version: "{{ item.version }}"
    force: true
    update: true
  loop: "{{ compose_external_repositories }}"

- name: Apply external service overlays
  ansible.builtin.copy:
    src: "{{ item.overlay }}/"
    dest: "{{ docker_compose_root }}/{{ item.name }}/"
    owner: root
    group: "{{ docker_compose_group }}"
    mode: "0664"
    directory_mode: "2775"
  loop: "{{ compose_external_repositories }}"
