---
- name: Check secret docker-data source
  ansible.builtin.stat:
    path: "{{ server_secrets_source_path }}/docker-data"
  register: secret_docker_data_source
  no_log: true

- name: Deploy secret docker-data configuration
  ansible.builtin.copy:
    src: "{{ server_secrets_source_path }}/docker-data/"
    dest: "{{ docker_data_root }}/"
    remote_src: true
  when: secret_docker_data_source.stat.isdir | default(false)
  no_log: true
