---
docker_system_prune_enabled: false
docker_system_prune_calendar: "Sun *-*-* 06:00:00"
docker_system_prune_max_wait_seconds: 7200
docker_system_prune_retry_seconds: 60
docker_system_prune_pull_quiet_period: 15m
