http:
  middlewares:
    event-manager-admin-frontend-security:
      headers:
        frameDeny: true
        permissionsPolicy: 'camera=(self), geolocation=(self), microphone=(), payment=(), usb=(), fullscreen=(self)'
        customResponseHeaders:
          Server: ''
          X-Permitted-Cross-Domain-Policies: 'none'

    event-manager-public-frontend-security:
      headers:
        frameDeny: true
        permissionsPolicy: 'camera=(self), geolocation=(self), microphone=(), payment=(), usb=(), fullscreen=(self "https://www.youtube-nocookie.com")'
        customResponseHeaders:
          Server: ''
          X-Permitted-Cross-Domain-Policies: 'none'
