http:
  middlewares:
    event-manager-admin-frontend-security:
      headers:
        contentSecurityPolicy: >-
          base-uri 'self'; default-src 'self'; object-src 'none'; script-src 'self' 'wasm-unsafe-eval' https://a.cacic.com.br; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://cdn.jsdelivr.net https://lh3.googleusercontent.com; font-src 'self' data:; connect-src 'self' https://a.cacic.com.br https://account.cacic.com.br https://cdn.jsdelivr.net https://fastly.jsdelivr.net https://glitchtip.cacic.com.br https://notifications.cacic.com.br https://unleash.cacic.com.br; frame-src 'self'; worker-src 'self' blob:; manifest-src 'self'; media-src 'self' blob:; form-action 'self'; frame-ancestors 'none'; trusted-types angular angular#bundler angular#unsafe-bypass default cacic#external-script; require-trusted-types-for 'script'; upgrade-insecure-requests
        frameDeny: true
        permissionsPolicy: 'camera=(self), geolocation=(self), microphone=(), payment=(), usb=(), fullscreen=(self)'
        customResponseHeaders:
          Server: ''
          X-Permitted-Cross-Domain-Policies: 'none'

    event-manager-public-frontend-security:
      headers:
        contentSecurityPolicy: >-
          base-uri 'self'; default-src 'self'; object-src 'none'; script-src 'self' 'wasm-unsafe-eval' https://a.cacic.com.br https://challenges.cloudflare.com; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob: https://cdn.jsdelivr.net https://lh3.googleusercontent.com; font-src 'self' data:; connect-src 'self' https://a.cacic.com.br https://account.cacic.com.br https://cdn.jsdelivr.net https://fastly.jsdelivr.net https://glitchtip.cacic.com.br https://notifications.cacic.com.br https://unleash.cacic.com.br; frame-src 'self' https://challenges.cloudflare.com https://www.youtube-nocookie.com; worker-src 'self' blob:; manifest-src 'self'; media-src 'self' blob:; form-action 'self'; frame-ancestors 'none'; trusted-types angular angular#bundler angular#unsafe-bypass default cacic#external-script; require-trusted-types-for 'script'; upgrade-insecure-requests
        frameDeny: true
        permissionsPolicy: 'camera=(self), geolocation=(self), microphone=(), payment=(), usb=(), fullscreen=(self "https://www.youtube-nocookie.com")'
        customResponseHeaders:
          Server: ''
          X-Permitted-Cross-Domain-Policies: 'none'
