---
compose_data_directories:
  - authentik
  - beszel
  - cacic-error-pages/html
  - cacic-account/postgres_data
  - cacic-account/redis_data
  - cacic-event-manager/db
  - cacic-event-manager/redis
  - cacic-novu/mongodb
  - crowdsec/opt/crowdsec
  - crowdsec/opt/crowdsec-db
  - crowdsec/traefikLogs
  - crowdsec/var/log/crowdsec
  - glitchtip/pg-data
  - glitchtip/uploads
  - grafana
  - immich/library
  - immich/model-cache
  - immich/postgres
  - infisical/pg_data
  - infisical/redis_data
  - keycloak/postgres_data
  - prometheus/data
  - seaweedfs/data/admin
  - seaweedfs/data/filer
  - seaweedfs/data/master
  - seaweedfs/data/s3
  - seaweedfs/data/volume
  - seaweedfs/postgres_data
  - shlink/db-data
  - typesense/analytics
  - typesense/data
  - umami/umami-db-data
  - unleash/postgres_data
  - uptime-kuma/data
  - vaultwarden
  - wud/store

compose_data_files:
  - path: crowdsec/var/log/auth.log
    mode: "0644"
    repair_empty_directory: true
  - path: prometheus/prometheus.yml
    mode: "0644"
