---
compose_projects:
  - cacic-error-pages
  - crowdsec
  - prometheus
  - prometheus-node
  - traefik
  - fake-smtp
  - authentik
  - keycloak
  - grafana
  - uptime-kuma
  - beszel-dashboard
  - seaweedfs
  - cacic-novu
  - cacic-account-manager
  - cacic-email-templates
  - cacic-event-manager
  - glitchtip
  - immich
  - infisical
  - shlink
  - typesense
  - umami-analytics
  - unleash
  - vaultwarden
  - wud-updater

compose_pull_before_up: true
compose_remove_orphans: true

compose_public_paths_moved_to_secrets:
  - cacic-error-pages/html
  - traefik/providers/crowdsec.yml

compose_required_secret_overlay_files:
  - cacic-account-manager/.env
  - cacic-event-manager/.env
  - cacic-novu/.env
  - keycloak/.env
  - seaweedfs/.env
  - seaweedfs/etc/seaweed/filer.toml
  - seaweedfs/etc/seaweed/s3_config.json
  - seaweedfs/etc/seaweed/security.toml
  - traefik/providers/crowdsec.yml

compose_secret_overlay_cleanup_patterns:
  - .env
  - "*.env"
  - "*.secret"
  - "*.secret.*"
  - crowdsec.yml

compose_secret_overlay_exclude_patterns:
  - acme.json
  - acme-ip.json

compose_retired_paths:
  - cacic-fctapp
  - cacic-fctapp-byebye
