---
firewall_apply_ipv4_policy: false

firewall_allowed_ssh_ipv4:
  - 200.145.0.0/16
  - 186.217.0.0/16

firewall_allowed_icmp_ipv4:
  - 200.145.0.0/16
  - 186.217.0.0/16

firewall_public_tcp_ports:
  - 80
  - 443

firewall_public_udp_ports:
  - 80
  - 443
