services:
  docs-private:
    image: ghcr.io/cacic-fct/docs-private:main
    restart: always
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.scope=docs-private"
      # Traefik - Proxy
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.docs-private.entryPoints=web, websecure"
      - "traefik.http.routers.docs-private.rule=Host(`docs.cacic.dev.br`)"
      - "traefik.http.routers.docs-private.tls=true"
      - "traefik.http.routers.docs-private.tls.certResolver=letsencrypt"
      # HTTP Service
      - "traefik.http.services.docs-private-svc.loadBalancer.server.port=3000"
      - "traefik.http.services.docs-private-svc.loadBalancer.passHostHeader=true"
      # Middlewares
      - "traefik.http.routers.docs-private.middlewares=authentik@docker"

  docs-private_watchtower:
    image: containrrr/watchtower
    restart: always
    env_file:
      - secrets.env
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_SCOPE=docs-private
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_HTTP_API_UPDATE=true
      - WATCHTOWER_HTTP_API_PERIODIC_POLLS=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik
    labels:
      - "com.centurylinklabs.watchtower.scope=docs-private"
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.docs-private-watchtower.entryPoints=websecure"
      - "traefik.http.routers.docs-private-watchtower.rule=Host(`watchtower.cacic.dev.br`) && PathPrefix(`/cacic-docs-private`)"
      - "traefik.http.routers.docs-private-watchtower.tls=true"
      - "traefik.http.routers.docs-private-watchtower.tls.certResolver=letsencrypt"
      - "traefik.http.routers.docs-private-watchtower.service=docs-private-watchtower-svc"
      - "traefik.http.services.docs-private-watchtower-svc.loadBalancer.server.port=8080"
      - "traefik.http.routers.docs-private-watchtower.middlewares=docs-private-stripprefix, noindex@file"
      # Remover o caminho /docs-private para redirecionar o pedido corretamente para a API
      - "traefik.http.middlewares.docs-private-stripprefix.stripprefix.prefixes=/cacic-docs-private"

networks:
  traefik:
    external: true
