services:
  email-templates:
    image: ghcr.io/cacic-fct/email-templates:main
    restart: always
    networks:
      - traefik
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^main$$"
      - "wud.trigger.include=docker.emailtemplates"
      - "wud.display.name=cacic-email-templates"
      - "wud.link.template=https://github.com/cacic-fct/email-templates/pkgs/container/email-templates"
      # Traefik - Proxy
      - "traefik.enable=true"
      # Router
      - "traefik.http.routers.email-templates.entryPoints=web, websecure"
      - "traefik.http.routers.email-templates.rule=Host(`emails.cacic.dev.br`)"
      - "traefik.http.routers.email-templates.tls=true"
      - "traefik.http.routers.email-templates.tls.certResolver=letsencrypt"
      - "traefik.http.routers.email-templates.tls.domains=emails.cacic.dev.br"
      # HTTP Service
      - "traefik.http.services.email-templates-svc.loadBalancer.server.port=4321"
      - "traefik.http.services.email-templates-svc.loadBalancer.passHostHeader=true"
      # Middlewares
      - "traefik.http.routers.email-templates.middlewares=email-templates-csp-mw"
      - "traefik.http.middlewares.email-templates-csp-mw.headers.contentSecurityPolicy=default-src 'self' cacic.dev.br; img-src *; style-src 'unsafe-inline'; object-src 'none'; script-src 'self' 'unsafe-inline'"

networks:
  traefik:
    external: true
