---
ansible_pull_deployment_telemetry_enabled: false
ansible_pull_verbosity: 2
ansible_pull_show_diff: true
ansible_pull_deployment_telemetry_wrapper_path: /usr/local/libexec/ansible-pull/github-deployment-telemetry-ansible-pull
ansible_pull_deployment_telemetry_repo_url: "{{ ansible_pull_repo_url }}"
ansible_pull_deployment_telemetry_environment: production
ansible_pull_deployment_telemetry_environment_url: ""
ansible_pull_deployment_telemetry_log_url: ""
ansible_pull_deployment_telemetry_production_environment: true
ansible_pull_deployment_telemetry_transient_environment: false
ansible_pull_deployment_telemetry_token_helper_path: ""
ansible_pull_deployment_telemetry_app_id: ""
ansible_pull_deployment_telemetry_app_slug: ""
ansible_pull_deployment_telemetry_app_installation_id: ""
ansible_pull_deployment_telemetry_app_private_key_path: ""
