services:
  master:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    volumes:
      - /home/shared/docker-data/seaweedfs/data/master:/data
    command: >
      master
      -ip=master
      -ip.bind=0.0.0.0
      -metricsPort=9324
      -mdir=/data
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^latest$$"
      - "wud.display.name=seaweedfs-master"
      - "wud.link.template=https://github.com/seaweedfs/seaweedfs/pkgs/container/seaweedfs"
    networks:
      - default

  volume:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    depends_on:
      - master
    volumes:
      - /home/shared/docker-data/seaweedfs/data/volume:/data
    command: >
      volume
      -mserver="master:9333"
      -ip.bind=0.0.0.0
      -port=8080
      -metricsPort=9325
      -dir=/data
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^latest$$"
      - "wud.display.name=seaweedfs-volume"
      - "wud.link.template=https://github.com/seaweedfs/seaweedfs/pkgs/container/seaweedfs"
    networks:
      - default

  filer:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    depends_on:
      - master
      - volume
      - db
    volumes:
      - /home/shared/docker-data/seaweedfs/data/filer:/data
      - ./etc/seaweed/security.toml:/etc/seaweed/security.toml:ro
      - ./etc/seaweed/filer.toml:/etc/seaweed/filer.toml:ro
    command: >
      filer
      -master="master:9333"
      -ip.bind=0.0.0.0
      -metricsPort=9326
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^latest$$"
      - "wud.display.name=seaweedfs-filer"
      - "wud.link.template=https://github.com/seaweedfs/seaweedfs/pkgs/container/seaweedfs"
    networks:
      - traefik
      - postgres_network
      - default

  admin:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    depends_on:
      - master
      - volume
      - filer
    volumes:
      - /home/shared/docker-data/seaweedfs/data/admin:/var/lib/seaweedfs-admin
    command: >
      admin
      -port=23646
      -masters="master:9333"
      -adminUser=admin
      -adminPassword=${SEAWEED_ADMIN_PASSWORD}
      -dataDir="/var/lib/seaweedfs-admin"
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^latest$$"
      - "wud.display.name=seaweedfs-admin"
      - "wud.link.template=https://github.com/seaweedfs/seaweedfs/pkgs/container/seaweedfs"
      - "traefik.enable=true"
      - "traefik.scope=public"
      - "traefik.http.routers.seaweed-admin.rule=Host(`storage.cacic.dev.br`)"
      - "traefik.http.routers.seaweed-admin.entrypoints=web, websecure"
      - "traefik.http.routers.seaweed-admin.service=seaweed-admin"
      - "traefik.http.services.seaweed-admin.loadbalancer.server.port=23646"
      - "traefik.http.routers.seaweed-admin.tls=true"
      - "traefik.http.routers.seaweed-admin.tls.certResolver=letsencrypt"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default

  s3:
    image: chrislusf/seaweedfs
    restart: unless-stopped
    depends_on:
      - master
      - volume
      - filer
    volumes:
      - /home/shared/docker-data/seaweedfs/data/s3:/data
      - ./etc/seaweed/s3_config.json:/etc/seaweed/s3_config.json:ro
      - ./etc/seaweed/security.toml:/etc/seaweed/security.toml:ro
    ports:
      - 8333:8333
    command: >
      -v=4
      s3
      -filer="filer:8888"
      -ip.bind=0.0.0.0
      -port=8333
      -metricsPort=9327
      -config=/etc/seaweed/s3_config.json
    labels:
      - "wud.watch=true"
      - "wud.watch.digest=true"
      - "wud.tag.include=^latest$$"
      - "wud.display.name=seaweedfs-s3"
      - "wud.link.template=https://github.com/seaweedfs/seaweedfs/pkgs/container/seaweedfs"
      - "traefik.enable=true"
      - "traefik.scope=public"
      - "traefik.http.routers.seaweed-s3.rule=Host(`s3.cacic.dev.br`)"
      - "traefik.http.routers.seaweed-s3.entrypoints=web, websecure"
      - "traefik.http.routers.seaweed-s3.service=seaweed-s3"
      - "traefik.http.middlewares.s3-headers.headers.customResponseHeaders.Transfer-Encoding="
      - "traefik.http.routers.seaweed-s3.middlewares=s3-headers"
      - "traefik.http.services.seaweed-s3.loadbalancer.server.port=8333"
      - "traefik.http.routers.seaweed-s3.tls=true"
      - "traefik.http.routers.seaweed-s3.tls.certResolver=letsencrypt"
      - "traefik.http.services.seaweed-s3.loadbalancer.passhostheader=true"
      - "traefik.http.middlewares.s3-headers.headers.customRequestHeaders.Host=s3.cacic.dev.br"
      - "traefik.docker.network=traefik"
    networks:
      - traefik
      - default

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: postgres
    volumes:
      - /home/shared/docker-data/seaweedfs/postgres_data:/var/lib/postgresql/data
    networks:
      - postgres_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h postgres -p 5432"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  traefik:
    external: true
  postgres_network:
  default:
