
services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    restart: always
    volumes:
      - /home/shared/docker-data/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock

    #    ports:
    #      - "3001:3001"  # <Host Port>:<Container Port>
    #      - "3307:3306"

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.kuma.entryPoints=websecure, web"
      - "traefik.http.routers.kuma.rule=Host(`status.cacic.dev.br`)"
      - "traefik.http.routers.kuma.tls=true"
      - "traefik.http.routers.kuma.tls.certResolver=letsencrypt"
      - "traefik.http.routers.kuma.tls.domains=status.cacic.dev.br"
      - "traefik.http.routers.kuma.service=kuma-svc"
      - "traefik.http.services.kuma-svc.loadBalancer.server.port=3001"
      - "traefik.http.routers.kuma.middlewares=authentik@docker"

    networks:
      - traefik
      - prometheus
networks:
  traefik:
    external: true
  prometheus:
    external: true
