services:
  mailcatcher:
    restart: unless-stopped
    image: dockage/mailcatcher:0.9.0
    ports:
      - "1025:1025"
    networks:
      - traefik
      - smtp
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.http.routers.fake-smtp.entryPoints=websecure, web"
      - "traefik.http.routers.fake-smtp.rule=Host(`smtp.cacic.dev.br`)"
      - "traefik.http.routers.fake-smtp.tls=true"
      - "traefik.http.routers.fake-smtp.tls.certResolver=letsencrypt"
      - "traefik.http.routers.fake-smtp.tls.domains=smtp.cacic.dev.br"
      - "traefik.http.routers.fake-smtp.middlewares=authentik@docker"
      - "traefik.http.routers.fake-smtp.service=fake-smtp-svc"
      - "traefik.http.services.fake-smtp-svc.loadBalancer.server.port=1080"

networks:
  traefik:
    external: true
  smtp:
    external: true
